---
name: Lint commit messages
on:
  pull_request:

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout source code

      - uses: wagoid/commitlint-github-action@v6
        name: Lint commit messages

