---
on:
  push:
    branches: [master]

permissions:
  contents: write
  pull-requests: write

name: Run release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          release-type: rust
          package-name: ${{ github.event.repository.name }}
          token: ${{ secrets.GH_SS_CLI_AUTH_TOKEN }}
